language: "en"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!*.md"
    - "!docs/**"
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches:
      - "main"
      - "master"
  tools:
    languagetool:
      enabled: false
chat:
  auto_reply: true
github_checks:
  annotations: true
  labels: true
tracking:
  issues: true
  prs: true